INSERT INTO <%- entityTableName %>(CREATION_DATE, NAME, DESCRIPTION, AMOUNT, TYPE) VALUES (CURRENT_TIMESTAMP(), 'fake1', 'description1', 1.0, 'ENUM_TYPE_1')
INSERT INTO <%- entityTableName %>(CREATION_DATE, NAME, DESCRIPTION, AMOUNT, TYPE) VALUES (CURRENT_TIMESTAMP(), 'fake2', 'description2', 2.0, 'ENUM_TYPE_2')
INSERT INTO <%- entityTableName %>(CREATION_DATE, NAME, DESCRIPTION, AMOUNT, TYPE) VALUES (CURRENT_TIMESTAMP(), 'fake3', 'description3', 2.0, 'ENUM_TYPE_3')
